name: ava_pdm_angelachantal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Maps
  google_maps_flutter: ^2.5.0
  
  # Location
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^16.0.0
  
  # HTTP
  http: ^1.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Images
  cached_network_image: ^3.3.1
  
  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.2
  json_serializable: ^6.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
